"""Check every quoted sentence in the README's skill-text table against the skill files it cites.

    git clone https://github.com/binance/binance-skills-hub /tmp/hub && git -C /tmp/hub checkout 9960c675
    python3 scripts/verify_skill_quotes.py /tmp/hub --out docs/skill-quotes-check.md

A quote is split at "…"; every fragment must appear (after dropping ** and backticks, curly quotes made straight,
whitespace collapsed) in a .md file under the hub's skills/. Exit 1 if any quote is not found.
"""
import argparse
import json
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def norm(s: str) -> str:
    s = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", s)        # markdown link -> its text
    s = s.replace("**", "").replace("`", "").replace("“", '"').replace("”", '"').replace("’", "'")
    return re.sub(r"\s+", " ", s).strip()


def table_rows(readme: str):
    rows = []
    for line in readme.splitlines():
        if not line.startswith("| ") or line.startswith("|---"):
            continue
        cell = line.split(" | ")[0][2:]
        quotes = re.findall(r'"([^"]{4,})"', cell)
        if not quotes or cell.startswith("Skill text"):
            continue
        cites = re.findall(r"\(([^()]*(?:\.md|query-token-audit)[^()]*)\)", cell)
        rows.extend({"quote": q, "cited": "; ".join(cites)} for q in quotes)
    return rows


def corpus(hub: str):
    base = os.path.join(hub, "skills")
    docs = {}
    for dp, _, fn in os.walk(base):
        for f in fn:
            if f.endswith(".md"):
                full = os.path.join(dp, f)
                docs[os.path.relpath(full, hub)] = norm(open(full, encoding="utf-8", errors="replace").read())
    return docs


def check(hub: str, readme_text: str):
    docs = corpus(hub)
    out = []
    for r in table_rows(readme_text):
        frags = [norm(x).strip(' .,"') for x in re.split(r"…|\.\.\.", r["quote"]) if norm(x).strip(' .,"')]
        hits = [sorted(p for p, t in docs.items() if fr in t) for fr in frags]
        found = all(hits)
        where = sorted(set(hits[0]).intersection(*map(set, hits[1:]))) if found else []
        out.append({**r, "found": found, "in": (where or sorted({p for h in hits for p in h}))[:2]})
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("hub")
    ap.add_argument("--readme", default=os.path.join(ROOT, "README.md"))
    ap.add_argument("--out")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--rev", help="hub commit, when the hub is a copy of its .md files without .git")
    a = ap.parse_args(argv)
    rows = check(a.hub, open(a.readme, encoding="utf-8").read())
    if a.json:
        print(json.dumps(rows, ensure_ascii=False))
    if a.out:
        rev = a.rev or subprocess.run(["git", "-C", a.hub, "rev-parse", "--short=8", "HEAD"], capture_output=True, text=True).stdout.strip()
        lines = [f"# Skill quotes in the README, checked against the skill text",
                 "",
                 f"`binance-skills-hub` commit `{rev}`. Generated by `python3 scripts/verify_skill_quotes.py <hub> --out {os.path.relpath(a.out, ROOT)}`.",
                 f"{sum(r['found'] for r in rows)} of {len(rows)} quotes found word for word (`**`, backticks and line breaks ignored; `…` marks a cut).",
                 "",
                 "| # | Quote in README | Cited as | Found in | Match |", "|---|---|---|---|---|"]
        for i, r in enumerate(rows, 1):
            q = r["quote"].replace("|", "\\|")
            lines.append(f"| {i} | \"{q}\" | {r['cited'] or '—'} | {', '.join('`' + p + '`' for p in r['in']) or '—'} | {'yes' if r['found'] else 'no'} |")
        open(a.out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    if not a.json:
        for r in rows:
            print(("OK  " if r["found"] else "MISS"), r["quote"][:90])
    return 0 if all(r["found"] for r in rows) else 1


if __name__ == "__main__":
    sys.exit(main())
